In [1]:
import pandas as pd

food_items = [
    "WHOPPER CHS","WHOPPER","SM FRY","LG FRY","SOFT DRINK",
    "REGULAR COMBO","BIG MAC","MCCHICKEN","FRENCH FRIES",
    "PEPSI","COKE","ZINGER BURGER","HOT WINGS","PIZZA",
    "GARLIC BREAD","PASTA","CAPPUCCINO","LATTE","MOCHA",
    "CHICKEN SANDWICH","VEG BURGER","NUGGETS","ONION RINGS",
    "MILKSHAKE","ICED COFFEE"
]

shopping_items = [
    "LAPTOP","HEADPHONES","MOUSE","KEYBOARD","MONITOR",
    "TOOTHPASTE","SHAMPOO","SOAP","BEDSHEET","TOWEL",
    "AIRPODS","IPHONE CASE","USB CABLE","RUNNING SHOES",
    "SPORTS SHOES","STUDY TABLE","CHAIR","T SHIRT",
    "JEANS","JACKET","POWER BANK","SMART WATCH",
    "BACKPACK","NOTEBOOK","WATER BOTTLE"
]

transport_items = [
    "CAB RIDE","AIRPORT RIDE","UBERX","UBER GO",
    "CITY RIDE","AIRPORT TRANSFER","METRO TICKET",
    "TRAIN PASS","TRAIN TICKET","SLEEPER TICKET",
    "FLIGHT TICKET","BOARDING PASS","BUS TICKET",
    "OLA MINI","OLA PRIME","PETROL","DIESEL",
    "PARKING FEE","TAXI RIDE","CAB BOOKING",
    "AUTO RIDE","METRO CARD","BUS PASS",
    "FUEL REFILL","TOLL PAYMENT"
]

food_merchants = [
    "Burger King","McDonalds","KFC","Dominos","Pizza Hut",
    "Starbucks","Subway","Taco Bell","Cafe Coffee Day","Burger Singh"
]

shopping_merchants = [
    "Amazon","Flipkart","Walmart","Target","Apple",
    "Best Buy","Nike","Adidas","IKEA","H&M"
]

transport_merchants = [
    "Uber","Ola","Metro","Railway","Air India",
    "Indigo","City Bus","Parking","Taxi Service","Fuel Station"
]

rows = []

for i in range(100):
    rows.append([
        food_merchants[i % len(food_merchants)],
        food_items[i % len(food_items)],
        "Food"
    ])

for i in range(100):
    rows.append([
        shopping_merchants[i % len(shopping_merchants)],
        shopping_items[i % len(shopping_items)],
        "Shopping"
    ])

for i in range(100):
    rows.append([
        transport_merchants[i % len(transport_merchants)],
        transport_items[i % len(transport_items)],
        "Transport"
    ])

extra_df = pd.DataFrame(
    rows,
    columns=["merchant", "item", "category"]
)

extra_df.to_csv("extra_300_rows.csv", index=False)

print(extra_df.shape)

(300, 3)

In [2]:
import pandas as pd

old_df = pd.read_csv("receipts.csv")

extra_df = pd.read_csv("extra_300_rows.csv")

combined_df = pd.concat(
    [old_df, extra_df],
    ignore_index=True
)

combined_df.to_csv(
    "receipts_final.csv",
    index=False
)

print("Old:", old_df.shape)
print("Extra:", extra_df.shape)
print("Combined:", combined_df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'receipts.csv'

In [3]:
import pandas as pd

old_df = pd.read_csv("receipts.csv")

extra_df = pd.read_csv("extra_300_rows.csv")

combined_df = pd.concat(
    [old_df, extra_df],
    ignore_index=True
)

combined_df.to_csv(
    "receipts_final.csv",
    index=False
)

print("Old:", old_df.shape)
print("Extra:", extra_df.shape)
print("Combined:", combined_df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'receipts.csv'

In [4]:
import pandas as pd

old_df = pd.read_csv("./dataset/receipts.csv")
extra_df = pd.read_csv("./extra_300_rows.csv")

combined_df = pd.concat(
    [old_df, extra_df],
    ignore_index=True
)

combined_df.to_csv(
    "receipts_final.csv",
    index=False
)

print("Old:", old_df.shape)
print("Extra:", extra_df.shape)
print("Combined:", combined_df.shape)

Old: (800, 3)
Extra: (300, 3)
Combined: (1100, 3)

In [5]:
import pandas as pd

df = pd.read_csv("receipts_final.csv")

print(df.shape)

df.head()

(1100, 3)

  merchant          item category
0  Dominos         Pizza     Food
1  Dominos        Burger     Food
2  Dominos         Fries     Food
3  Dominos        Coffee     Food
4  Dominos  Garlic Bread     Food

In [6]:
df["text"] = df["merchant"] + " " + df["item"]

df.head()

  merchant          item category                  text
0  Dominos         Pizza     Food         Dominos Pizza
1  Dominos        Burger     Food        Dominos Burger
2  Dominos         Fries     Food         Dominos Fries
3  Dominos        Coffee     Food        Dominos Coffee
4  Dominos  Garlic Bread     Food  Dominos Garlic Bread

In [7]:
X = df["text"]

y = df["category"]

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

print(X_vectorized.shape)

(1100, 285)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [11]:
from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [12]:
import pickle

pickle.dump(
    model,
    open("receipt_model.pkl", "wb")
)

pickle.dump(
    vectorizer,
    open("vectorizer.pkl", "wb")
)

print("New Model Saved")

New Model Saved

In [15]:
sample = 

vector = vectorizer.transform(sample)

prediction = model.predict(vector)

print(prediction)

['Transport']