In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: scikit-learn in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/reciept-ml/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

df = pd.read_csv("dataset/receipts.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/receipts.csv'

In [2]:
import pandas as pd

df = pd.read_csv("dataset/receipts.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/receipts.csv'

In [3]:
import pandas as pd

df = pd.read_csv("dataset/receipts.csv")

print(df.shape)

(800, 3)

In [4]:
df.head()

  merchant          item category
0  Dominos         Pizza     Food
1  Dominos        Burger     Food
2  Dominos         Fries     Food
3  Dominos        Coffee     Food
4  Dominos  Garlic Bread     Food

In [5]:
import pandas as pd

df = pd.read_csv("dataset/receipts.csv")

df["text"] = df["merchant"] + " " + df["item"]

X = df["text"]
y = df["category"]

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [9]:
from sklearn.metrics import accuracy_score

preds = model.predict(X_test)

print(accuracy_score(y_test, preds))

1.0

In [10]:
import pandas as pd

df = pd.read_csv("dataset/receipts.csv")

print(df.shape)

(800, 3)

In [11]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [12]:
df = pd.read_csv("dataset/receipts.csv")

df.head()

  merchant          item category
0  Dominos         Pizza     Food
1  Dominos        Burger     Food
2  Dominos         Fries     Food
3  Dominos        Coffee     Food
4  Dominos  Garlic Bread     Food

In [13]:
print(df.shape)

(800, 3)

In [14]:
df["text"] = df["merchant"] + " " + df["item"]

df.head()

  merchant          item category                  text
0  Dominos         Pizza     Food         Dominos Pizza
1  Dominos        Burger     Food        Dominos Burger
2  Dominos         Fries     Food         Dominos Fries
3  Dominos        Coffee     Food        Dominos Coffee
4  Dominos  Garlic Bread     Food  Dominos Garlic Bread

In [15]:
X = df["text"]

y = df["category"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

NameError: name 'X_vectorized' is not defined

In [17]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
df = pd.read_csv("dataset/receipts.csv")

df.head()

  merchant          item category
0  Dominos         Pizza     Food
1  Dominos        Burger     Food
2  Dominos         Fries     Food
3  Dominos        Coffee     Food
4  Dominos  Garlic Bread     Food

In [19]:
print(df.shape)

(800, 3)

In [20]:
df["text"] = df["merchant"] + " " + df["item"]

df.head()

  merchant          item category                  text
0  Dominos         Pizza     Food         Dominos Pizza
1  Dominos        Burger     Food        Dominos Burger
2  Dominos         Fries     Food         Dominos Fries
3  Dominos        Coffee     Food        Dominos Coffee
4  Dominos  Garlic Bread     Food  Dominos Garlic Bread

In [21]:
X = df["text"]

y = df["category"]

In [22]:
vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

print(X_vectorized.shape)

(800, 205)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
print(df.shape)

(800, 4)

In [25]:
X_vectorized = vectorizer.fit_transform(X)
print(X_vectorized.shape)

(800, 205)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(640, 205)
(160, 205)

In [27]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [28]:
from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [29]:
sample = ["Dominos Pizza"]

sample_vector = vectorizer.transform(sample)

prediction = model.predict(sample_vector)

print(prediction)

['Food']

In [30]:
sample = ["Uber Airport Ride"]

In [30]:
sample = ["Uber Airport Ride"]

In [31]:
sample = ["Amazon Laptop"]

In [32]:
sample = ["Apollo Pharmacy Paracetamol"]

In [33]:
import pickle

pickle.dump(model, open("receipt_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Saved Successfully")

Saved Successfully

In [34]:
import pickle

pickle.dump(model, open("receipt_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model Saved")

Model Saved

In [36]:
sample = ["Uber Airport Ride"]

sample_vector = vectorizer.transform(sample)

prediction = model.predict(sample_vector)

print(prediction)]

SyntaxError: unmatched ']' (1965608898.py, line 7)

In [37]:
sample = ["Uber Airport Ride"]

sample_vector = vectorizer.transform(sample)

prediction = model.predict(sample_vector)

print(prediction)

['Transport']